"use server";

import { format } from "date-fns";
import { and, eq, lt, sql } from "drizzle-orm";
import { db } from "@/db";
import { activeCodes, attendanceAudit, students } from "@/db/schema";

/**
 * Registers attendance for a student using a volatile code.
 *
 * @param cui - Student CUI.
 * @param code - Attendance code generated by a teacher.
 * @returns A promise that resolves to an object indicating success or failure.
 */
export async function registerAttendanceAction(cui: string, code: string) {
  try {
    const student = await db.query.students.findFirst({
      where: eq(students.cui, cui),
    });
    if (!student) throw new Error("CUI no registrado");

    const activeCode = await db.query.activeCodes.findFirst({
      where: eq(activeCodes.code, code.toUpperCase()),
    });

    if (!activeCode) {
      throw new Error("Código inválido o ya no está disponible");
    }

    if (new Date() > activeCode.expiresAt) {
      await db.delete(activeCodes).where(eq(activeCodes.code, activeCode.code));
      throw new Error("El código ha expirado");
    }

    const today = format(new Date(), "yyyy-MM-dd");
    const existing = await db.query.attendanceAudit.findFirst({
      where: and(
        eq(attendanceAudit.studentCui, cui),
        eq(attendanceAudit.courseCode, activeCode.courseCode),
        eq(attendanceAudit.groupLetter, activeCode.groupLetter),
        sql`DATE(${attendanceAudit.timestamp}) = ${today}`,
      ),
    });

    if (existing) {
      throw new Error(
        "Ya has registrado asistencia para este curso y grupo hoy",
      );
    }

    await db.insert(attendanceAudit).values({
      courseCode: activeCode.courseCode,
      courseName: activeCode.courseName,
      groupLetter: activeCode.groupLetter,
      studentCui: cui,
      studentName: student.name,
      timestamp: new Date(),
    });

    db.delete(activeCodes)
      .where(lt(activeCodes.expiresAt, new Date()))
      .catch((err) => console.error("Cleanup error:", err));

    return { success: true };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : "Error desconocido",
    };
  }
}
