import { relations } from "drizzle-orm";
import { pgTable, serial, text, timestamp } from "drizzle-orm/pg-core";

/**
 * Database table for storing course information.
 * Key fields: code (PK), name, abbreviation, and comma-separated groups.
 */
export const courses = pgTable("courses", {
  code: text("code").primaryKey(),
  name: text("name").notNull(),
  abbreviation: text("abbreviation").notNull(),
  groups: text("groups").notNull(),
});

/**
 * Defines relations for the courses table.
 * A course can have many teachers assigned to it.
 */
export const coursesRelations = relations(courses, ({ many }) => ({
  teachers: many(teachers),
}));

/**
 * Database table for storing teacher accounts.
 * Key fields: username (PK), password (hashed/plain as per current impl), name, and courseCode (FK).
 */
export const teachers = pgTable("teachers", {
  username: text("username").primaryKey(),
  password: text("password").notNull(),
  name: text("name").notNull(),
  courseCode: text("course_code").references(() => courses.code, {
    onDelete: "set null",
  }),
});

/**
 * Defines relations for the teachers table.
 * Each teacher is assigned to exactly one course.
 */
export const teachersRelations = relations(teachers, ({ one }) => ({
  course: one(courses, {
    fields: [teachers.courseCode],
    references: [courses.code],
  }),
}));

/**
 * Database table for storing student records.
 * Key fields: cui (PK) and name.
 */
export const students = pgTable("students", {
  cui: text("cui").primaryKey(),
  name: text("name").notNull(),
});

/**
 * Database table for auditing attendance registration events.
 * Captures snapshots of course, group, and student info.
 */
export const attendanceAudit = pgTable("attendance_audit", {
  id: serial("id").primaryKey(),
  timestamp: timestamp("timestamp").defaultNow().notNull(),
  courseCode: text("course_code"),
  courseName: text("course_name"),
  groupLetter: text("group_letter"),
  studentCui: text("student_cui"),
  studentName: text("student_name"),
});

/**
 * Database table for storing active, volatile attendance codes generated by teachers.
 * These codes have a short TTL (Time To Live) defined by expiresAt.
 */
export const activeCodes = pgTable("active_codes", {
  code: text("code").primaryKey(),
  courseCode: text("course_code").notNull(),
  courseName: text("course_name").notNull(),
  groupLetter: text("group_letter").notNull(),
  teacherUsername: text("teacher_username").notNull(),
  expiresAt: timestamp("expires_at").notNull(),
});
